---
name: Broken links check

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  check:
    name: check links check
    runs-on: ubuntu-latest
    steps:
      - name: generate token
        uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: "${{ secrets.BOT_APP_ID }}"
          private_key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: checkout
        uses: actions/checkout@v3
        with:
          token: "${{ steps.generate-token.outputs.token }}"

      - name: scan for broken links
        uses: lycheeverse/lychee-action@v1
        id: lychee
        env:
          GITHUB_TOKEN: "${{ steps.generate-token.outputs.token }}"
        with:
          args: --verbose --no-progress --exclude-mail './**/*.md'

      - name: find link checker issue
        id: broken-link-check-issue
        uses: micalevisk/last-issue-action@v2
        with:
          state: open
          labels: |
            broken-links

      - name: update issue
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: broken links detected 🔗
          issue-number: "${{ steps.broken-link-check-issue.outputs.issue-number }}"
          content-filepath: ./lychee/out.md
          token: "${{ steps.generate-token.outputs.token }}"
          labels: |
            broken-links